version: "3.8"
services:
   mudblazorui:
      build:
        context: .
        dockerfile: Dockerfile.mudblazorui
      environment:
        VIRTUAL_HOST: mudblazorui.${MY_HOST:-localhost}
      restart: always

   identitydemo:
      build:
        context: .
        dockerfile: Dockerfile.identitydemo
      environment:
        VIRTUAL_HOST: identitydemo.${MY_HOST:-localhost}
      restart: always

   mvcblazordemo:
      build:
        context: .
        dockerfile: Dockerfile.mvcblazordemo
      environment:
        VIRTUAL_HOST: mvcblazordemo.${MY_HOST:-localhost}
      restart: always

   demositelist:
      build:
        context: .
        dockerfile: Dockerfile.demositelist
      environment:
        VIRTUAL_HOST: ${MY_HOST:-localhost}
      restart: always
      
   nginx-proxy:
      image: jwilder/nginx-proxy
      environment:
        DEFAULT_HOST: ${MY_HOST:-localhost}
      ports:
        - "8880:80"
        - "8443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
      restart: always