version: "3.8"
services:
   nginx-proxy:
      image: jwilder/nginx-proxy
      ports:
        - "8880:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
      restart: always

   mudblazorui:
      build: mudblazorui
      environment:
        VIRTUAL_HOST: mudblazorui.localhost
      restart: always

   identitydemo:
      build: identitydemo
      environment:
        VIRTUAL_HOST:  identitydemo.localhost
      restart: always

