version: "3.8"
services:
   mudblazorui:
      build:
        context: .
        dockerfile: Dockerfile.mudblazorui
      environment:
        VIRTUAL_HOST: mudblazorui.${MY_HOST:-localhost}
        LETSENCRYPT_HOST: mudblazorui.${MY_HOST:-localhost}
        LETSENCRYPT_EMAIL: hostmaster@example.com
      restart: always

   identitydemo:
      build:
        context: .
        dockerfile: Dockerfile.identitydemo
      environment:
        VIRTUAL_HOST: identitydemo.${MY_HOST:-localhost}
        LETSENCRYPT_HOST: identitydemo.${MY_HOST:-localhost}
        LETSENCRYPT_EMAIL: hostmaster@example.com
      restart: always

   mvcblazordemo:
      build:
        context: .
        dockerfile: Dockerfile.mvcblazordemo
      environment:
        VIRTUAL_HOST: mvcblazordemo.${MY_HOST:-localhost}
        LETSENCRYPT_HOST: mvcblazordemo.${MY_HOST:-localhost}
        LETSENCRYPT_EMAIL: hostmaster@example.com
      restart: always

   demositelist:
      build:
        context: .
        dockerfile: Dockerfile.demositelist
      environment:
        VIRTUAL_HOST: ${MY_HOST:-localhost}
        LETSENCRYPT_HOST: ${MY_HOST:-localhost}
        LETSENCRYPT_EMAIL: hostmaster@example.com
      restart: always
      
   proxy:
      image: jwilder/nginx-proxy:alpine
      environment:
        DEFAULT_HOST: ${MY_HOST:-localhost}
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./certs:/etc/nginx/certs:ro
        - ./vhost.d:/etc/nginx/vhost.d
        - ./html:/usr/share/nginx/html
        - ./conf.d:/etc/nginx/conf.d        
      labels:
        - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"  
      restart: always

   letsencrypt:
     image: jrcs/letsencrypt-nginx-proxy-companion
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - ./certs:/etc/nginx/certs:rw
       - ./vhost.d:/etc/nginx/vhost.d:rw
       - ./html:/usr/share/nginx/html:rw
     environment:
       - NGINX_PROXY_CONTAINER=proxy_proxy_1