version: "3.8"
services:
   mudblazorui:
      image: mudblazorui
      environment:
        VIRTUAL_HOST: mudblazorui.localhost
      restart: always

   identitydemo:
      image: identitydemo
      environment:
        VIRTUAL_HOST: identitydemo.localhost
      restart: always

   demositelist:
      image: demositelist
      environment:
        VIRTUAL_HOST: localhost
      restart: always
      
   nginx-proxy:
      image: jwilder/nginx-proxy
      environment:
        DEFAULT_HOST: localhost
      ports:
        - "8880:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
<<<<<<< HEAD
      restart: always
=======
      restart: always
>>>>>>> cc7606aa1d9f4431c8b948833aae5626e018d914
